# Generated by Django 3.0.5 on 2020-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=500),
            preserve_default=False,
        ),
    ]
