# Generated by Django 3.0.5 on 2020-04-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_account_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='item',
            field=models.CharField(default='Saving for...', max_length=200),
        ),
    ]
